name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: 11
          apps: sbt sbtn
      - uses: coursier/cache-action@v5
      - name: Compile
        run: sbt clean test:compile
      - name: Run tests
        run: sbt example-client-jvm-test/test msocket-http/test example-server/test
